---
micronaut:
  application:
    name: artifactory-badges
  server:
    port: 8080
#    netty:
#      log-level: info
  metrics:
    enabled: true

---
endpoints:
  health:
    enabled: true

---
logging:
  level:
    root: info
    io.micronaut.http.server: trace
    io.micronaut.http.client: trace
    io.micronaut.context: debug

---
shields:
  host: https://img.shields.io

---
artifactory:
  host: localhost
  port: 8081
  user: username
  token: password
