---
micronaut:
  application:
    name: artifactory-badges
  server:
    port: 8080
  metrics:
    enabled: true

---
endpoints:
  health:
    enabled: true

---
shields:
  host: https://img.shields.io

---
artifactory:
  host: localhost
  port: 8081
  user: username
  token: password
